### ISSUE TITLE
关于设定属性小小问题

### ISSUE THREAD

**Issue by jarecl** [nyaoouo/FFxivPythonCraft#1]
[player]
lv=80
craft=2758
control=2917
cp=657

月下的禁断是2907
是开了部队特效的那个buff吗加工精度+10

**Comment by nyaoouo** [comment]
是的，不过加工属性上的变动对脚本效率没有太大影响，可改可不改（指设定）

**Comment by jarecl** [comment]
可惜， 我也不会生产，纯靠目前这个算法的话，2分钟成功一个左右，不过辛苦了

**Comment by jarecl** [comment]
最新这一版，成功率高不少，谢谢
