### ISSUE TITLE
main闪退

### ISSUE THREAD

**Issue by Weisswire** [nyaoouo/FFxivPythonCraft#3]
萌新请教一下大佬_(:з」∠)_，点击main.py之后闪退有解嘛...都按照步骤操作嘞

**Comment by nyaoouo** [comment]
请提供报错相关，如果是lv2clv index out of range 请关闭config内MemoryFixStatus选项

**Comment by Weisswire** [comment]
pymem.exception.CouldNotOpenProcess: Could not open process: 5356
大概是这样_(:з」∠)_

**Comment by nyaoouo** [comment]
1.请更新最新版本
2.请在64位python环境下给予管理员权限运行

**Comment by Weisswire** [comment]
ヽ(￣▽￣)و好的！谢谢啦！
